# GitHub Actions workflow for reqtracker integration
# Place this file in .github/workflows/update-requirements.yml

name: Update Requirements

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.py'
      - 'requirements/**'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install reqtracker
      run: |
        pip install reqtracker

    - name: Generate requirements
      run: |
        # Create requirements directory if it doesn't exist
        mkdir -p requirements

        # Generate base requirements
        reqtracker analyze ./src --output requirements/base.txt --version-strategy compatible

        # Generate production requirements (exact versions)
        reqtracker analyze ./src --mode static --output requirements/production.txt --version-strategy exact

        # Generate development requirements (includes tests)
        reqtracker analyze . --exclude-dirs docs --output requirements/development.txt --version-strategy compatible

    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain requirements/)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit updated requirements
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add requirements/
        git commit -m "chore(deps): update requirements.txt files"

    - name: Push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  dependency-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install reqtracker
      run: pip install reqtracker

    - name: Check dependencies
      run: |
        echo "## Dependency Analysis" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        # Analyze current dependencies
        echo "### Current Dependencies" >> $GITHUB_STEP_SUMMARY
        reqtracker track ./src --mode static > current_deps.txt
        echo '```' >> $GITHUB_STEP_SUMMARY
        cat current_deps.txt >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY

        # Check for any issues
        if reqtracker analyze ./src --mode static --quiet; then
          echo "Dependency analysis completed successfully" >> $GITHUB_STEP_SUMMARY
        else
          echo "Issues found in dependency analysis" >> $GITHUB_STEP_SUMMARY
          exit 1
        fi
